name: run-test-dart

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - packages/dart/test/**
      - packages/dart/lib/**
      - packages/dart/pubspec.yaml
      - .github/workflows/run-test-dart.yml
  workflow_dispatch:

jobs:
  run-test-dart:
    runs-on: ${{ matrix.os }}
    name: Test Dart ${{ matrix.sdk }} on ${{ matrix.os }}
    env:
      working-directory: ./packages/dart
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        sdk: ["3.5", stable, beta]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get
        working-directory: ${{ env.working-directory }}

      - name: Run tests
        run: dart test
        working-directory: ${{ env.working-directory }}
