name: Module test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-test-dart:
    runs-on: ${{ matrix.os }}
    name: Test Dart ${{ matrix.node_version }} on ${{ matrix.os }}
    env:
      working-directory: ./packages/dart
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        sdk: [ "3.5", stable, beta ]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test
